theme = "Solarized-Osaka"
# theme = "whale"

[editor]
line-number = "relative"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-completion = true
auto-format = true
color-modes = true
cursorline = true

[editor.statusline]
left = ["mode", "spinner", "file-base-name", "file-modification-indicator"]
separator = "▶"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
charactger = "▏"

normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[keys.normal]
H = "goto_first_nonwhitespace"
L = "goto_line_end_newline"
"ret" = "goto_word"

[keys.insert]
j.k = "normal_mode"
