# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format ="$directory $character"
right_format = "$time"

[character] # The name of the module we are configuring is 'character'
success_symbol = '[⬤](bold red)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✗](bold red)'

[directory]
truncation_length = 200
truncate_to_repo = false
format = '[$path](white)'

[time]
format = '[$time](bold magenta)'
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
